### ISSUE TITLE
[Suggestion] Allow players to leash one entity to another ("chain leading")

### ISSUE THREAD

**Issue by vico93** [quaoz/BetterLeads#10]
Basically, make it possible to a "leading" entity to pull another behind using the lead.

Reference implementations for this is both [Chain Lead](https://modrinth.com/mod/chain_lead) ([GH](https://github.com/codehz-mcmods/chain-lead)) and the older [Entity Spring](https://legacy.curseforge.com/minecraft/mc-mods/entity-spring) (honestly i didnt see any difference in physics between the spring and vanilla lead).

In Chain Lead it works as the following:

> Make lead chainable, just sneak and right click another mob with lead item to create chain.

**Comment by quaoz** [comment]
Added in [v1.2.2](https://github.com/quaoz/BetterLeads/releases/tag/v1.2.2).
