### ISSUE TITLE
Crashing in 1.20 Minecraft server startup

### ISSUE THREAD

**Issue by Nihilanthy** [quaoz/BetterLeads#8]
This mod isn't working in 1.20 Minecraft server, it crashes in  startup... it seems to be a problem with quilt build pointing to build 5, as the 1.20 only has 4 builds, idk, i'm not a modder. pls do a fix, I want to use this on my server asf...

File of my server starting:
[logmod.txt](https://github.com/quaoz/BetterLeads/files/12573646/logmod.txt)

**Comment by quaoz** [comment]
This should be fixed, if it isn't please reopen the issue. Sorry for the delay.
